name: Create Release Tarballs

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up build tools
        run: |
          sudo apt-get install -y \
            build-essential \
            autoconf \
            autoconf-archive \
            automake \
            curl \
            libcurl4-openssl-dev \
            git \
            libev-dev \
            libtool \
            pkg-config \
            sqlite

      - name: Generate configure script
        run: autoreconf -fi

      - name: Run configure
        run: ./configure

      - name: Create .tar.gz source tarball
        run: make dist

      - name: Create .zip source tarball
        run: make dist-zip

      - name: List files to verify tarball creation
        run: ls -lah

      - name: Upload .tar.gz release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./clboss-*.tar.gz
          asset_name: clboss-${{ github.event.release.tag_name }}.tar.gz
          asset_content_type: application/gzip

      - name: Upload .zip release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./clboss-*.zip
          asset_name: clboss-${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip
